# SWMAL Demo

## Keras to catagorical demo

In [1]:
import numpy as np
from keras.utils import to_categorical

y = np.array([1, 2, 0, 4, -1])
y_cat = to_categorical(y)

print(y_cat)

# prints 
#[[0. 1. 0. 0. 0.]  => i=0, class 1
# [0. 0. 1. 0. 0.]  => i=1, class 2
# [1. 0. 0. 0. 0.]  => i=2, class 0
# [0. 0. 0. 0. 1.]  => i=3, class 4
# [0. 0. 0. 0. 1.]] => i=4, also class 4!
#                      NOTE: no class 3

ImportError: /opt/anaconda-2025.06/lib/python3.12/site-packages/tensorflow/python/platform/../../libtensorflow_framework.so.2: undefined symbol: _ZN4absl12lts_202501275MutexD1Ev