# L04 - Cost function

#### Qa Given the following $\mathbf{x}^{(i)}$'s, we have to construct and print the $\mathbf X$ matrix in python.

$$
    \def\rem#1{}
    \rem{ITMAL: CEF def and LaTeX commands v01, remember: no newlines in defs}
    \rem{MACRO eq: equation <#1:lhs> <#2:rhs>}
    \def\eq#1#2{#1 &=& #2\\}
    \rem{MACRO arr: array <#1:columns (lcr..)> <#2:content>}
    \def\ar#1#2{\begin{array}{#1}#2\end{array}}
    \rem{MACRO ac: array column vector <#1:columns (lcr..)> <#2:content>}
    \def\ac#1#2{\left[\ar{#1}{#2}\right]}
    \rem{MACRO st: subscript text <#1:content>}
    \def\st#1{_{\textrm{#1}}}
    \rem{MACRO norm: norm caligari L <#1:content>}
    \def\norm#1{{\cal L}_{#1}}
    \rem{MACRO obs: ??}
    \def\obs#1#2{#1_{\textrm{\scriptsize obs}}^{\left(#2\right)}}
    \rem{MACRO diff: math differetial operator <#1:content>}
    \def\diff#1{\mathrm{d}#1} 
    \rem{MACRO half: shorthand for 1/2}
    \def\half{\frac{1}{2}}
    \rem{MACRO pfrac: partial fraction <#1:numenator> <#2:denumenator>}
    \def\pfrac#1#2{\frac{\partial~#1}{\partial~#2}}
    \rem{MACRO dfrac: differetial operator fraction <#1:numenator> <#2:denumenator>}
    \def\dfrac#1#2{\frac{\mathrm{d}~#1}{\mathrm{d}#2}}
    \rem{MACRO pown: power and parantesis (train/test..) <#1:content>}
    \def\pown#1{^{(#1)}}
    \rem{MACROS powi, pown: shorthands for power (i) and (n)}
    \def\powni{\pown{i}}
    \def\pownn{\pown{n}}
    \rem{MACROS powtest, powertrain: power (test) and (train)}
    \def\powtest{\pown{\textrm{\scriptsize test}}}
    \def\powtrain{\pown{\textrm{\scriptsize train}}}
    \rem{MACRO boldmatrix: bold matix/vector notation} 
    \def\boldmatrix#1{\mathbf{#1}} 
    \rem{MACROS X,Z,x,y,w: bold X,Z,x etc.} 
    \def\bX{\boldmatrix{X}}
    \def\bZ{\boldmatrix{Z}}
    \def\bx{\boldmatrix{x}}
    \def\by{\boldmatrix{y}}
    \def\bw{\boldmatrix{w}}
    \def\bp{\boldmatrix{p}}
    \def\bq{\boldmatrix{q}}
    \def\bz{\boldmatrix{z}}
    \def\btheta{{\boldsymbol\theta}}
    \def\bSigma{{\boldsymbol\Sigma}}
    \rem{MACROS stpred, sttrue: shorthand for subscript 'pred' and 'true'}
    \def\stpred{\st{pred}~}
    \def\sttrue{\st{true}~}
    \rem{MACROS ypred, ytrue:   shorthand for scalar y 'pred' and 'true'}
    \def\ytrue{y\sttrue}
    \def\ypred{y\stpred} 
    \rem{MACROS bypred, bytrue: shorthand for vecor y 'pred' and 'true'} 
    \def\bypred{\boldmatrix{y}\stpred}
    \def\bytrue{\boldmatrix{y}\sttrue} 
\bx\powni =
    \ar{rl}{
      \bx\pown{1} &= \ac{c}{ 1\\ 2\\ 3} \\
      \bx\pown{2} &= \ac{c}{ 4\\ 2\\ 1} \\
      \bx\pown{3} &= \ac{c}{ 3\\ 8\\ 5} \\
      \bx\pown{4} &= \ac{c}{-9\\-1\\ 0}
    }
$$
Using np.array and without using built-in python lists or the numpy matrix subclass

Since we have to use np.array the given column vectors are simply defined using np.array as shown in the code and np.vstack is then used to construct the full matrix since it is given that we should not construct using python lists.


In [ ]:
# Qa

import numpy as np

y_true = np.array([1,2,3,4]) # Needed later

# Code for Qa: Creating and printing of the full matrix
#Setting up the given columns vectors:
x1=np.array([[1],[2],[3]])
x2=np.array([[4],[2],[1]])
x3=np.array([[3],[8],[5]])
x4=np.array([[-9],[-1],[0]])
#Constructing the matrix
X=np.vstack((x1.T, x2.T, x3.T, x4.T))
print(f"X={X}")


X=[[ 1  2  3]
 [ 4  2  1]
 [ 3  8  5]
 [-9 -1  0]]


#### Qb Implement the $\norm{1}$ and $\norm{2}$ norms for vectors in python.
We first have to make a low-level implementation of the $\norm{1}$ and $\norm{2}$ norms using only ```+```, ```*``` and power ```**```. Without using any libraries or build in python functions. We then have to test the implementations against build in functions like ```numpy.linalg.norm```. Finally we have to optimize $\norm{2}$ such that it uses the matrix multiplication operator instead of an explicit sum and call this function ```L2MatrixMult```. Python functions are here allowed but it must be pythonic.

We start by creating the low level implementation using while loops. In the L1 implementation we note that we have to make sure we get the absolute value which is done using an if statement. This is not necessary in the L2 implementation since the product is summed but we take the square root of the sum at the end. These implementation are then tested against ```numpy.linalg.norm```, producing no difference as can be seen in the print.

The L2 function is then optimized using the matrix multiplication operator @, which means we can simply use the dot product implementation, which can be directly calculated as q @ q and then find the square root.

As can be seen below, the implementation of both the low level function and the optimized version passes the tests.


In [ ]:
# Code for Qb: implementation of low-level L1, L2 and L2Dot functions.
def L1(x):
    assert x.shape[0]>0 and x.ndim==1, "Not a 1-D vector" #Error check from Qe
    s=0
    n=x.shape[0]
    i=0
    while i<n:
        xi=x[i]
        if xi<0:
            xi=-xi
            
        s=s+xi
        i=i+1
    return s


def L2(x):
    assert x.shape[0]>0 and x.ndim==1, "Not a 1-D vector" #Error check from Qe
    s=0
    n=x.shape[0]
    i=0
    while i<n:
        s=s+(x[i]*x[i])
        i=i+1
    return s**0.5

def L2dot(q):
    assert q.shape[0]>0 and q.ndim==1, "Not a 1-D vector" #Error check from Qe
    s=0
    n=q.shape[0]
    i=0
    while i<n:
        s=s+(q[i]*q[i])
        i=i+1
    return s

#Test against linalg.norm
q=np.array([1, 5, -3, 0])
diff1=L1(q)-np.linalg.norm(q,ord=1)
diff2=L2(q)-np.linalg.norm(q,ord=2)
print(f"testdiff1={diff1}")
print(f"testdiff2={diff2}")

#L2 is then optimized using the matrix multiplication operator as:
def L2MatrixMult(q):
    return (q @ q)**0.5


# TEST vectors: here I test your implementation...calling your L1() and L2() functions
tx=np.array([1, 2, 3, -1])
ty=np.array([3,-1, 4,  1])

expected_d1=8.0
expected_d2=4.242640687119285

d1=L1(tx-ty)
d2=L2(tx-ty)

print(f"tx-ty={tx-ty}, d1-expected_d1={d1-expected_d1}, d2-expected_d2={d2-expected_d2}")

eps=1E-9 
import math
# NOTE: remember to import 'math' for fabs for the next two lines..
assert math.fabs(d1-expected_d1)<eps, "L1 dist seems to be wrong" 
assert math.fabs(d2-expected_d2)<eps, "L2 dist seems to be wrong" 

print("OK(part-1)")

# comment-in once your L2MatrixMult fun is ready...
d2 = L2MatrixMult(tx-ty)
print(f"d2[matrix mult]-expected_d2 = {d2-expected_d2}")
assert math.fabs(d2-expected_d2)<eps, "L2MatrixMult dist seem to be wrong" 
print("OK(part-2)")

testdiff1=0.0
testdiff2=0.0
tx-ty=[-2  3 -1 -2], d1-expected_d1=0.0, d2-expected_d2=0.0
OK(part-1)
d2[matrix mult]-expected_d2 = 0.0
OK(part-2)


### Qc Construct the Root Mean Square Error (RMSE) function (Equation 2-1 [HOML]).
We have to construct an RMSE function and evaluate it based on the $\bX$ matrix and $\by$ from Qa.

The RMSE function can be constructed based on the L2 function from Qb, since RMSE is defined as:
$$
    \ar{rl}{
        \textrm{MSE} &= \frac{1}{n} \sum_{i=1}^{n} (\hat{Y}_i-Y_i)^2 \\
        \textrm{RMSE}&= \sqrt{\textrm{MSE}}\
    }
$$

Where
$$
    \ar{rl}{
         \textrm{L2}=\sqrt{(\hat{Y}_i-Y_i)^2}
    }
$$
Which gives
$$
    \ar{rl}{
        \textrm{RMSE}&= \frac{1}{\sqrt{n}} \textrm{L2}
    }
$$
This can then be implemented as shown in the code below which produces a result that is the same as the expected to the given decimals.



In [ ]:
# Code for Qc: Implementation of the RMSE function
def RMSE(ypred, y):
    assert y.shape[0]>0 and y.ndim==1 and ypred.shape[0]==y.shape[0], "Error in vectors" #Error check from Qe
    n=y.shape[0]
    return L2(ypred-y)/(n**0.5)
    

# Dummy h function:
def h(X):    
    if X.ndim!=2:
        raise ValueError("excpeted X to be of ndim=2, got ndim=",X.ndim)
    if X.shape[0]==0 or X.shape[1]==0:
        raise ValueError("X got zero data along the 0/1 axis, cannot continue")
    return X[:,0]

# Calls your RMSE() function:
r=RMSE(h(X), y_true)

# TEST vector:
eps=1E-9
expected=6.57647321898295
print(f"RMSE={r}, diff={r-expected}")
assert math.fabs(r-expected)<eps, "your RMSE dist seems to be wrong" 

print("OK")

RMSE=6.576473218982953, diff=2.6645352591003757e-15
OK


#### Qd Similar construct the Mean Absolute Error (MAE) function (Equation 2-2 [HOML]) and evaluate it.
We similarly have to construct the MAE using $\norm{1}$ from Qb.

MAE is the mean absolute error defined as:
$$
    \ar{rl}{
        \textrm{MAE} &= \frac{1}{n} \sum_{i=1}^{n} |\hat{Y}_i-Y_i| \\
    }
$$

Where
$$
    \ar{rl}{
        \textrm{L1} &= \sum_{i=1}^{n} |\hat{Y}_i-Y_i| \\
    }
$$

And we thus have:
$$
    \ar{rl}{
        \textrm{MAE} &= \frac{1}{n} \textrm{L1}
    }
$$
Which can then be implemented and thereby, as expected, produces a difference of zero




In [ ]:
# Code for Qd
def MAE(ypred, y):
    assert y.shape[0]>0 and y.ndim==1 and ypred.shape[0]==y.shape[0], "Error in vectors" #Error check from Qe
    n=y.shape[0]
    return L1(ypred-y)/n


# Calls your MAE function:
r=MAE(h(X), y_true)

# TEST vector:
expected=3.75
print(f"MAE={r}, diff={r-expected}")
assert math.fabs(r-expected)<eps, "MAE dist seems to be wrong" 

print("OK")

MAE=3.75, diff=0.0
OK


#### Qe Robust Code 
We have to add asserts or exceptions that checks the $\hat\by$-$\by$ sizes of the MSE and MAE function. We also have to add error checking to all the previously tested L2() and L1() functions.

To checks that the sizes of the input vectors in the MSE and MAE function are correct, an assert is added at the beginning which checks that the vectors are one dimensional and of the same size as:
```python
assert x.shape[0]>0 and x.ndim==1 and x.shape[0]==y.shape[0], "Error in vectors"
```
This is added to the previous code as instructed and the tests are re-run.

For the previously tested L2() and L1() functions and assert is similarly added to ensure the input is a vector, as is expected.
```python
assert x.shape[0]>0 and x.ndim==1, "Not a 1-D vector"
```

It should be noted that a check for column and row vectors is also often used but because the definitions of which are used in this context are a bit fuzzy, for example is the y_true vector described as column, but given as a row, this check is excluded here.


### Qf Conclusion
Conclude on all the previous exercises for this section, max. 10- to 20-lines.

In these exercises we first learned to construct a matrix as a numpy array by assembling column vectors without using python lists as an aid which is a useful tool for assemling the data matrix in machine learning. We furthmore learned and worked with how the norms are defined and implemented, both on a low level as well as a higher level using the matrix multiplication operator. The importance of this was then illustrated through its relation to the cost function, where the common RMSE and MAE functions where construced through use of the previous norm functions. This implementation and process clearly illustrated the defintion and meaning of the loss functions as well as how they could be coded by working from the ground up. Lastly, the importance of data validation was also discussed and a fail-fast approach was implemented in the code to make sure any error is appears as quickly as possible. These are all very important machine learning concept, which concerns the fundamental coding and understanding of how the processes works. The overall learning outcomes of the exercises could thereby be said to be basic understanding of the python implementation of vector-matrix formulations along with a fundamental understanding of how the loss functions are build up and an introduction to fail-fast approach. 
